-- 신고(report)·유저 차단(user_block) 추가 — Google Play UGC 정책의 앱 내 신고·차단 요건.
-- Hibernate가 PostgreSQLDialect로 생성하는 형태(V1과 동일한 규칙)로 작성했다: 식별자는 전부 인용,
-- @Enumerated(STRING)은 varchar + check 제약. report의 대상(target_type, target_id)은 다형 참조라 FK를 걸지 않는다.

create table "report" (id bigint generated by default as identity, created_at timestamp(6), detail varchar(500), reason varchar(255) check (reason in ('SPAM','INAPPROPRIATE','FRAUD','HARASSMENT','OTHER')) not null, status varchar(255) check (status in ('PENDING','RESOLVED')) not null, target_id bigint not null, target_type varchar(255) check (target_type in ('POST','USER')) not null, reporter_id bigint not null, primary key (id));

create table "user_block" (id bigint generated by default as identity, created_at timestamp(6), blocked_id bigint not null, blocker_id bigint not null, primary key (id));

alter table "report" add constraint UK_report_reporter_target unique (reporter_id, target_type, target_id);

alter table "user_block" add constraint UK_user_block_pair unique (blocker_id, blocked_id);

alter table "report" add constraint FK_report_reporter foreign key (reporter_id) references "user" (user_id);

alter table "user_block" add constraint FK_user_block_blocker foreign key (blocker_id) references "user" (user_id);

alter table "user_block" add constraint FK_user_block_blocked foreign key (blocked_id) references "user" (user_id);
