services:
  postgres:
    image: postgres:16
    container_name: allargando-postgres
    environment:
      POSTGRES_DB: allargando
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - allargando-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  allargando-postgres-data:
